services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
  dynamodb-init:
    image: amazon/aws-cli
    depends_on:
      - dynamodb
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    volumes:
      - ./local-dynamodb:/scripts
    entrypoint: ["sh", "/scripts/create-tables.sh"]
